spring.application.name=SGPT-BACKEND
# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sgpt_db
spring.datasource.username=sgpt_user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Opcional: configuración de Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
